[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-gen-text-binoculars"
version = "0.1.0"
description = "Batch AI-text detection via Falcon* Binoculars (T4/A100 friendly)"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "BSD-3-Clause" }
authors = [{ name = "DeepSee" }]

[tool.setuptools.packages.find]
include = ["ai_gen_text*", "experimental*", "binoculars*"]
